---
title: "Medical Appointment No Shows"
output: html_notebook
---

Libraries

```{r}
library(dplyr)
```


Load data, rename columns

```{r}
data <- read.csv("../data/No-show-Issue-Comma-300k.csv")

colnames(data) <- c("age", "gender", "appointment_registration", "appointment_data", "dayofweek_apptmt", "show_up",
                    "diabetes", "alcoholism", "hypertension", "handicap", "smoker", "scholarship", "tuberculosis",
                    "sms_reminder", "daydiff_regist_appt")

d <- data

```


Clean up dates

```{r}
#Registration

d$appointment_registration = as.POSIXct(as.character(d$appointment_registration),"%Y-%m-%d T%H:%M:%SZ",tz = "Brazil/East")

d = mutate(d, weekday_registration = as.factor(format(d$appointment_registration,"%a")))
d = mutate(d, day_registration = as.numeric(as.integer(format(d$appointment_registration,"%d"))))
d = mutate(d, month_registration = as.numeric(format(d$appointment_registration,"%m")))
d = mutate(d, date_registration = as.numeric(format(d$appointment_registration,"%D")))
d = mutate(d, hour_registration = as.numeric(format(d$appointment_registration,"%H")))
d = mutate(d, minute_registration = as.numeric(format(d$appointment_registration,"%M")))
d = mutate(d, day_of_year_registration = as.numeric(format(d$appointment_registration,"%j")))
d = mutate(d, week_of_year_registration = as.numeric(format(d$appointment_registration,"%U")))
d = mutate(d, am_pm_registration = as.factor(format(d$appointment_registration,"%p")))

#Appointment

d$appointment_data = as.POSIXct(as.character(d$appointment_data),"%Y-%m-%d T%H:%M:%SZ",tz = "Brazil/East")

d = mutate(d, weekday_appointment = as.factor(format(d$appointment_data,"%a")))
d = mutate(d, day_appointment = as.numeric(as.integer(format(d$appointment_data,"%d"))))
d = mutate(d, month_appointment = as.numeric(format(d$appointment_data,"%m")))
d = mutate(d, date_appointment = as.numeric(format(d$appointment_data,"%D")))
d = mutate(d, day_of_year_appointment = as.numeric(format(d$appointment_data,"%j")))
d = mutate(d, week_of_year_appointment = as.numeric(format(d$appointment_data,"%U")))

```

```{r}
plot(d$day_of_year_appointment, d$day_of_year_registration, col = d$show_up)
```


